nohup: ignoring input
2025-01-07T07:33:21.166-0800 I CONTROL  [initandlisten] MongoDB starting : pid=1182 port=27017 dbpath=/data/db 64-bit host=5300af1cb477
2025-01-07T07:33:21.166-0800 I CONTROL  [initandlisten] db version v3.6.8
2025-01-07T07:33:21.166-0800 I CONTROL  [initandlisten] git version: 8e540c0b6db93ce994cc548f000900bdc740f80a
2025-01-07T07:33:21.166-0800 I CONTROL  [initandlisten] OpenSSL version: OpenSSL 1.1.1f  31 Mar 2020
2025-01-07T07:33:21.166-0800 I CONTROL  [initandlisten] allocator: tcmalloc
2025-01-07T07:33:21.166-0800 I CONTROL  [initandlisten] modules: none
2025-01-07T07:33:21.166-0800 I CONTROL  [initandlisten] build environment:
2025-01-07T07:33:21.166-0800 I CONTROL  [initandlisten]     distarch: x86_64
2025-01-07T07:33:21.166-0800 I CONTROL  [initandlisten]     target_arch: x86_64
2025-01-07T07:33:21.166-0800 I CONTROL  [initandlisten] options: { storage: { dbPath: "/data/db" } }
2025-01-07T07:33:21.166-0800 I -        [initandlisten] Detected data files in /data/db created by the 'wiredTiger' storage engine, so setting the active storage engine to 'wiredTiger'.
2025-01-07T07:33:21.166-0800 I STORAGE  [initandlisten] wiredtiger_open config: create,cache_size=7347M,session_max=20000,eviction=(threads_min=4,threads_max=4),config_base=false,statistics=(fast),cache_cursors=false,compatibility=(release="3.0",require_max="3.0"),log=(enabled=true,archive=true,path=journal,compressor=snappy),file_manager=(close_idle_time=100000),statistics_log=(wait=0),verbose=(recovery_progress),
2025-01-07T07:33:28.777-0800 I STORAGE  [initandlisten] WiredTiger message [1736264008:777960][1182:0x7fc4f70b7ac0], txn-recover: Main recovery loop: starting at 1/20992
2025-01-07T07:33:30.477-0800 I STORAGE  [initandlisten] WiredTiger message [1736264010:477155][1182:0x7fc4f70b7ac0], txn-recover: Recovering log 1 through 2
2025-01-07T07:33:31.270-0800 I STORAGE  [initandlisten] WiredTiger message [1736264011:270613][1182:0x7fc4f70b7ac0], txn-recover: Recovering log 2 through 2
2025-01-07T07:33:31.869-0800 I STORAGE  [initandlisten] WiredTiger message [1736264011:869385][1182:0x7fc4f70b7ac0], txn-recover: Set global recovery timestamp: 0
2025-01-07T07:33:31.993-0800 I CONTROL  [initandlisten] 
2025-01-07T07:33:31.993-0800 I CONTROL  [initandlisten] ** WARNING: Access control is not enabled for the database.
2025-01-07T07:33:31.993-0800 I CONTROL  [initandlisten] **          Read and write access to data and configuration is unrestricted.
2025-01-07T07:33:31.993-0800 I CONTROL  [initandlisten] ** WARNING: You are running this process as the root user, which is not recommended.
2025-01-07T07:33:31.993-0800 I CONTROL  [initandlisten] 
2025-01-07T07:33:31.993-0800 I CONTROL  [initandlisten] ** WARNING: This server is bound to localhost.
2025-01-07T07:33:31.993-0800 I CONTROL  [initandlisten] **          Remote systems will be unable to connect to this server. 
2025-01-07T07:33:31.993-0800 I CONTROL  [initandlisten] **          Start the server with --bind_ip <address> to specify which IP 
2025-01-07T07:33:31.993-0800 I CONTROL  [initandlisten] **          addresses it should serve responses from, or with --bind_ip_all to
2025-01-07T07:33:31.993-0800 I CONTROL  [initandlisten] **          bind to all interfaces. If this behavior is desired, start the
2025-01-07T07:33:31.993-0800 I CONTROL  [initandlisten] **          server with --bind_ip 127.0.0.1 to disable this warning.
2025-01-07T07:33:31.993-0800 I CONTROL  [initandlisten] 
2025-01-07T07:33:32.180-0800 I FTDC     [initandlisten] Initializing full-time diagnostic data capture with directory '/data/db/diagnostic.data'
2025-01-07T07:33:32.184-0800 I NETWORK  [initandlisten] waiting for connections on port 27017
2025-01-07T07:33:49.977-0800 I NETWORK  [listener] connection accepted from 127.0.0.1:60240 #1 (1 connection now open)
2025-01-07T07:33:50.087-0800 I NETWORK  [conn1] received client metadata from 127.0.0.1:60240 conn1: { application: { name: "MongoDB Shell" }, driver: { name: "MongoDB Internal Client", version: "3.6.8" }, os: { type: "Linux", name: "Ubuntu", architecture: "x86_64", version: "20.04" } }
2025-01-07T07:34:14.915-0800 I STORAGE  [conn1] createCollection: chatbot.users with generated UUID: 3c0d9c53-02ec-406e-98c0-c96b442e5ded
2025-01-07T07:36:13.588-0800 I NETWORK  [conn1] end connection 127.0.0.1:60240 (0 connections now open)
2025-01-07T07:45:05.574-0800 I NETWORK  [listener] connection accepted from 127.0.0.1:60244 #2 (1 connection now open)
2025-01-07T07:45:05.575-0800 I NETWORK  [conn2] received client metadata from 127.0.0.1:60244 conn2: { driver: { name: "PyMongo|c", version: "4.10.1" }, os: { type: "Linux", name: "Linux", architecture: "x86_64", version: "5.3.0-1032-aws" }, platform: "CPython 3.8.10.final.0", env: { container: { runtime: "docker" } } }
2025-01-07T07:45:06.470-0800 I NETWORK  [conn2] end connection 127.0.0.1:60244 (0 connections now open)
2025-01-07T07:46:01.266-0800 I NETWORK  [listener] connection accepted from 127.0.0.1:60246 #3 (1 connection now open)
2025-01-07T07:46:01.267-0800 I NETWORK  [conn3] received client metadata from 127.0.0.1:60246 conn3: { driver: { name: "PyMongo|c", version: "4.10.1" }, os: { type: "Linux", name: "Linux", architecture: "x86_64", version: "5.3.0-1032-aws" }, platform: "CPython 3.8.10.final.0", env: { container: { runtime: "docker" } } }
2025-01-07T07:46:02.171-0800 I NETWORK  [conn3] end connection 127.0.0.1:60246 (0 connections now open)
2025-01-07T07:46:12.874-0800 I NETWORK  [listener] connection accepted from 127.0.0.1:60248 #4 (1 connection now open)
2025-01-07T07:46:12.874-0800 I NETWORK  [conn4] received client metadata from 127.0.0.1:60248 conn4: { driver: { name: "PyMongo|c", version: "4.10.1" }, os: { type: "Linux", name: "Linux", architecture: "x86_64", version: "5.3.0-1032-aws" }, platform: "CPython 3.8.10.final.0", env: { container: { runtime: "docker" } } }
2025-01-07T07:46:13.771-0800 I NETWORK  [conn4] end connection 127.0.0.1:60248 (0 connections now open)
